language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: 
  - pip install coveralls
notifications:
  email:
    recipients:
      - joshuago78@gmail.com
script:
  coverage run --source=shapes test.py
after_success:
  coveralls
